const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const crypto = require('crypto');
const Database = require('better-sqlite3');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;
const ADMIN_KEY = process.env.ADMIN_KEY || 'change-this-admin-key';
app.set('trust proxy', 1);
const PUBLIC_URL = (process.env.PUBLIC_URL || '').replace(/\/$/, '');
const dbPath = process.env.DB_PATH || path.join(__dirname, 'novahub.db');
const db = new Database(dbPath);
db.pragma('journal_mode = WAL');

function esc(v) { return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function clean(v,max=160){return String(v??'').trim().slice(0,max)}
function base(req){return PUBLIC_URL || `${req.protocol}://${req.get('host')}`}

// Core schema + safe migrations for upgrades from v6.
db.exec(`
CREATE TABLE IF NOT EXISTS creators (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, niche TEXT, bio TEXT, avatar_url TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, creator_id INTEGER NOT NULL, slug TEXT UNIQUE NOT NULL, title TEXT NOT NULL, media_url TEXT, published INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT UNIQUE NOT NULL, first_seen TEXT DEFAULT CURRENT_TIMESTAMP, last_seen TEXT DEFAULT CURRENT_TIMESTAMP, source TEXT, medium TEXT, campaign TEXT);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, creator_id INTEGER, post_id INTEGER, event_type TEXT NOT NULL, session_id TEXT NOT NULL, source TEXT, medium TEXT, campaign TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS revenue (id INTEGER PRIMARY KEY AUTOINCREMENT, source TEXT NOT NULL, creator_id INTEGER, period TEXT NOT NULL, impressions INTEGER DEFAULT 0, clicks INTEGER DEFAULT 0, revenue REAL DEFAULT 0, currency TEXT DEFAULT 'USD', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS monetization_sources (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, provider TEXT, status TEXT DEFAULT 'pending', placement TEXT, notes TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);
function hasCol(table,col){return db.prepare(`PRAGMA table_info(${table})`).all().some(x=>x.name===col)}
if(!hasCol('posts','body')) db.exec('ALTER TABLE posts ADD COLUMN body TEXT DEFAULT ""');
if(!hasCol('posts','category')) db.exec('ALTER TABLE posts ADD COLUMN category TEXT DEFAULT "Lifestyle"');
if(!hasCol('posts','meta_description')) db.exec('ALTER TABLE posts ADD COLUMN meta_description TEXT DEFAULT ""');
if(!hasCol('creators','disclosure')) db.exec('ALTER TABLE creators ADD COLUMN disclosure TEXT DEFAULT "Personaje virtual de ficción."');

if (db.prepare('SELECT COUNT(*) c FROM creators').get().c === 0) {
  const ins=db.prepare('INSERT INTO creators(slug,name,niche,bio,avatar_url,disclosure) VALUES(?,?,?,?,?,?)');
  ins.run('luna','Luna Nova','Lifestyle & fashion','Personaje virtual de ficción que comparte ideas de estilo, fotografía y vida cotidiana desde una perspectiva creativa.','https://placehold.co/900x900?text=Luna+Nova','Personaje virtual de ficción.');
  ins.run('aria','Aria Vega','Wellness & routines','Creadora virtual de ficción enfocada en hábitos, movimiento, organización personal y bienestar cotidiano.','https://placehold.co/900x900?text=Aria+Vega','Personaje virtual de ficción.');
}
const creators=db.prepare('SELECT * FROM creators ORDER BY id').all();
const countPosts=db.prepare('SELECT COUNT(*) c FROM posts').get().c;
if(countPosts<6){
  const bySlug=Object.fromEntries(creators.map(c=>[c.slug,c]));
  const add=db.prepare('INSERT OR IGNORE INTO posts(creator_id,slug,title,media_url,published,body,category,meta_description,created_at) VALUES(?,?,?,?,?,?,?,?,?)');
  const rows=[
    [bySlug.luna?.id,'luna-estilo-sin-complicarse','Estilo sin complicarse','https://placehold.co/1200x800?text=Luna+%7C+Estilo',1,'Luna propone una idea sencilla: construir un estilo reconocible no depende de tener un armario enorme. Elegir una paleta, repetir prendas que funcionan y reservar un detalle especial para cada look puede hacer que la rutina se sienta más personal. En NovaHub, este tipo de publicaciones busca inspirar ideas visuales sin presentar al personaje como una persona real.','Estilo','Ideas de estilo cotidiano de Luna Nova, un personaje virtual de ficción.','2026-09-08T10:00:00Z'],
    [bySlug.luna?.id,'luna-diario-visual','Cómo crear un diario visual','https://placehold.co/1200x800?text=Luna+%7C+Diario+visual',1,'Un diario visual puede ser una colección de pequeños momentos: una textura, una combinación de colores, una calle, un café o una prenda que quieras recordar. Luna usa este formato como recurso narrativo para construir continuidad entre sus publicaciones y convertir una imagen aislada en una historia breve.','Creatividad','Una guía breve y original sobre diarios visuales narrada por Luna Nova.','2026-09-07T10:00:00Z'],
    [bySlug.luna?.id,'luna-colores-para-fotos','Paletas de color para fotografías','https://placehold.co/1200x800?text=Luna+%7C+Colores',1,'Trabajar con tres colores principales ayuda a que una sesión de fotografías tenga una identidad consistente. Una fórmula útil es elegir un tono dominante, uno secundario y un pequeño acento. Luna convierte esa regla en un recurso visual recurrente para sus publicaciones.','Fotografía','Consejos de composición y color para fotografías de lifestyle.','2026-09-06T10:00:00Z'],
    [bySlug.aria?.id,'aria-rutina-realista','Una rutina que sí cabe en el día','https://placehold.co/1200x800?text=Aria+%7C+Rutina',1,'Aria plantea las rutinas como pequeñas decisiones repetibles. En lugar de una lista imposible, su formato favorito combina unos minutos de movimiento, una pausa sin pantalla y una tarea concreta que pueda cerrarse antes de pasar a la siguiente. El objetivo del personaje es compartir una idea práctica, no vender una transformación milagrosa.','Bienestar','Una rutina sencilla y realista presentada por Aria Vega.','2026-09-08T12:00:00Z'],
    [bySlug.aria?.id,'aria-organizar-semana','Organizar la semana en 15 minutos','https://placehold.co/1200x800?text=Aria+%7C+Organizacion',1,'Aria divide la planificación semanal en tres bloques: lo imprescindible, lo importante y lo que puede esperar. Después reserva espacios de descanso y deja margen para imprevistos. El método funciona mejor cuando la lista final es corta y visible, en lugar de intentar controlar cada minuto.','Productividad','Método breve de planificación semanal y prioridades.','2026-09-07T12:00:00Z'],
    [bySlug.aria?.id,'aria-movimiento-cotidiano','Movimiento cotidiano sin complicarlo','https://placehold.co/1200x800?text=Aria+%7C+Movimiento',1,'No todo el movimiento necesita convertirse en una sesión formal. Caminar, subir escaleras, estirarse durante una pausa o salir un momento al exterior también pueden formar parte de un día activo. Aria utiliza estas ideas como contenido editorial general y no como consejo médico.','Movimiento','Ideas generales para incorporar más movimiento cotidiano.','2026-09-06T12:00:00Z']
  ];
  for(const r of rows) if(r[0]) add.run(...r);
}

app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'100kb'}));
app.use(express.static(path.join(__dirname,'public')));
const eventLimiter=rateLimit({windowMs:60000,max:120,standardHeaders:true,legacyHeaders:false});
const adminLimiter=rateLimit({windowMs:15*60000,max:30,standardHeaders:true,legacyHeaders:false});
function admin(req,res,next){if(clean(req.headers['x-admin-key'],256)!==ADMIN_KEY)return res.status(401).json({error:'admin_required'});next()}
function sessionId(){return crypto.randomBytes(18).toString('hex')}

app.get('/api/bootstrap',(req,res)=>{
 const creators=db.prepare(`SELECT c.id,c.slug,c.name,c.niche,c.bio,c.avatar_url,(SELECT COUNT(*) FROM events e WHERE e.creator_id=c.id AND e.event_type='content_view') views FROM creators c ORDER BY views DESC,c.id`).all();
 const posts=db.prepare(`SELECT p.id,p.slug,p.title,p.media_url,p.creator_id,c.name creator_name,p.category,p.meta_description FROM posts p JOIN creators c ON c.id=p.creator_id WHERE p.published=1 ORDER BY p.created_at DESC`).all();
 res.json({creators,posts});
});
app.post('/api/session',eventLimiter,(req,res)=>{const sid=clean(req.body.session_id,100)||sessionId();const source=clean(req.body.source,80),medium=clean(req.body.medium,80),campaign=clean(req.body.campaign,120);db.prepare(`INSERT INTO sessions(session_id,source,medium,campaign) VALUES(?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET last_seen=CURRENT_TIMESTAMP`).run(sid,source,medium,campaign);res.json({session_id:sid})});
app.post('/api/event',eventLimiter,(req,res)=>{const allowed=new Set(['page_view','content_view','click','conversion']);const type=clean(req.body.event_type,30);if(!allowed.has(type))return res.status(400).json({error:'invalid_event'});const sid=clean(req.body.session_id,100);if(!sid)return res.status(400).json({error:'session_required'});const creator_id=Number(req.body.creator_id)||null,post_id=Number(req.body.post_id)||null,source=clean(req.body.source,80),medium=clean(req.body.medium,80),campaign=clean(req.body.campaign,120);const recent=db.prepare(`SELECT id FROM events WHERE session_id=? AND event_type=? AND COALESCE(post_id,0)=COALESCE(?,0) AND created_at >= datetime('now','-10 seconds') LIMIT 1`).get(sid,type,post_id);if(!recent)db.prepare(`INSERT INTO events(creator_id,post_id,event_type,session_id,source,medium,campaign) VALUES(?,?,?,?,?,?,?)`).run(creator_id,post_id,type,sid,source,medium,campaign);res.json({ok:true,deduped:!!recent})});
app.get('/api/stats',adminLimiter,admin,(req,res)=>{const views=db.prepare("SELECT COUNT(*) c FROM events WHERE event_type IN ('page_view','content_view')").get().c,pageViews=db.prepare("SELECT COUNT(*) c FROM events WHERE event_type='page_view'").get().c,clicks=db.prepare("SELECT COUNT(*) c FROM events WHERE event_type='click'").get().c,conversions=db.prepare("SELECT COUNT(*) c FROM events WHERE event_type='conversion'").get().c,sessions=db.prepare('SELECT COUNT(*) c FROM sessions').get().c,rev=db.prepare('SELECT COALESCE(SUM(revenue),0) v,COALESCE(SUM(impressions),0) i,COALESCE(SUM(clicks),0) c FROM revenue').get();const creators=db.prepare(`SELECT c.name,c.slug,COALESCE(SUM(CASE WHEN e.event_type='content_view' THEN 1 ELSE 0 END),0) views,COALESCE((SELECT SUM(r.revenue) FROM revenue r WHERE r.creator_id=c.id),0) revenue FROM creators c LEFT JOIN events e ON e.creator_id=c.id GROUP BY c.id ORDER BY views DESC`).all();const campaigns=db.prepare("SELECT COALESCE(NULLIF(campaign,''),'direct') campaign,COUNT(*) events FROM events GROUP BY campaign ORDER BY events DESC LIMIT 20").all();const sources=db.prepare('SELECT source,COALESCE(SUM(impressions),0) impressions,COALESCE(SUM(clicks),0) clicks,COALESCE(SUM(revenue),0) revenue FROM revenue GROUP BY source ORDER BY revenue DESC').all();res.json({views,pageViews,clicks,conversions,sessions,revenue:rev.v,monetized_impressions:rev.i,rpm:rev.i?(rev.v/rev.i)*1000:0,ctr:rev.i?(rev.c/rev.i)*100:0,creators,campaigns,sources})});
app.post('/api/revenue',adminLimiter,admin,(req,res)=>{const source=clean(req.body.source,100),period=clean(req.body.period,20),creator_id=Number(req.body.creator_id)||null,impressions=Math.max(0,Number(req.body.impressions)||0),clicks=Math.max(0,Number(req.body.clicks)||0),revenue=Math.max(0,Number(req.body.revenue)||0);if(!source||!period)return res.status(400).json({error:'source_and_period_required'});db.prepare('INSERT INTO revenue(source,creator_id,period,impressions,clicks,revenue,currency) VALUES(?,?,?,?,?,?,?)').run(source,creator_id,period,impressions,clicks,revenue,'USD');res.json({ok:true})});

function layout({title,description,canonical,body,ogImage=''}){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${ogImage?`<meta property="og:image" content="${esc(ogImage)}">`:''}<link rel="stylesheet" href="/styles.css"></head><body><header><div class="wrap nav"><a class="brand" href="/">NovaHub</a><nav><a href="/">Inicio</a><a href="/#creators">Modelos</a><a href="/#feed">Contenido</a><a href="/about.html">Sobre NovaHub</a><a href="/contact.html">Contacto</a></nav></div></header><main>${body}</main><footer><div class="wrap">© NovaHub · <a href="/about.html">Sobre</a> · <a href="/terms.html">Términos</a> · <a href="/privacy.html">Privacidad</a> · <a href="/contact.html">Contacto</a></div></footer><script src="/ads-config.js"></script></body></html>`}

app.get('/modelo/:slug',(req,res)=>{const c=db.prepare('SELECT * FROM creators WHERE slug=?').get(clean(req.params.slug,80));if(!c)return res.status(404).send(layout({title:'Modelo no encontrada — NovaHub',description:'El perfil solicitado no existe.',canonical:`${base(req)}/modelo/${esc(req.params.slug)}`,body:'<div class="wrap page"><h1>Modelo no encontrada</h1><p>El perfil solicitado no está disponible.</p><a class="btn" href="/">Volver al inicio</a></div>'}));const posts=db.prepare('SELECT * FROM posts WHERE creator_id=? AND published=1 ORDER BY created_at DESC').all(c.id);const cards=posts.map(p=>`<article class="card post"><a href="/contenido/${esc(p.slug)}"><img src="${esc(p.media_url)}" alt="${esc(p.title)}"><div><span class="pill">${esc(p.category)}</span><h2>${esc(p.title)}</h2><p>${esc(p.meta_description||p.body.slice(0,150))}</p></div></a></article>`).join('');const body=`<div class="wrap profile"><section class="profile-head"><img src="${esc(c.avatar_url)}" alt="${esc(c.name)}"><div><span class="pill">${esc(c.niche||'Creadora virtual')}</span><h1>${esc(c.name)}</h1><p>${esc(c.bio)}</p><p class="muted">${esc(c.disclosure)}</p></div></section><section><h2>Contenido de ${esc(c.name)}</h2><div class="grid">${cards||'<p>Aún no hay publicaciones.</p>'}</div></section><section class="notice"><b>Transparencia:</b> ${esc(c.disclosure)} Las publicaciones son editoriales y de entretenimiento.</section></div>`;res.send(layout({title:`${c.name} — NovaHub`,description:c.bio,canonical:`${base(req)}/modelo/${c.slug}`,ogImage:c.avatar_url,body}))});

app.get('/contenido/:slug',(req,res)=>{const p=db.prepare('SELECT p.*,c.name creator_name,c.slug creator_slug,c.avatar_url FROM posts p JOIN creators c ON c.id=p.creator_id WHERE p.slug=? AND p.published=1').get(clean(req.params.slug,100));if(!p)return res.status(404).send(layout({title:'Contenido no encontrado — NovaHub',description:'La publicación solicitada no existe.',canonical:`${base(req)}/contenido/${esc(req.params.slug)}`,body:'<div class="wrap page"><h1>Contenido no encontrado</h1><a class="btn" href="/">Volver al inicio</a></div>'}));const articleLd={"@context":"https://schema.org","@type":"Article","headline":p.title,"description":p.meta_description,"datePublished":p.created_at,"author":{"@type":"Organization","name":"NovaHub Editorial"},"publisher":{"@type":"Organization","name":"NovaHub"},"image":p.media_url};const paragraphs=p.body.split(/\n+/).map(x=>`<p>${esc(x)}</p>`).join('');const body=`<div class="wrap article"><div class="article-meta"><a href="/modelo/${esc(p.creator_slug)}">${esc(p.creator_name)}</a><span>·</span><span>${esc(p.category)}</span></div><h1>${esc(p.title)}</h1><p class="lead">${esc(p.meta_description)}</p><img class="article-image" src="${esc(p.media_url)}" alt="${esc(p.title)}"><div class="article-copy">${paragraphs}</div><aside class="notice">Este artículo forma parte de una colección de contenido original de NovaHub. ${esc(p.creator_name)} es un personaje virtual de ficción.</aside><a class="btn" href="/modelo/${esc(p.creator_slug)}">Ver perfil de ${esc(p.creator_name)}</a></div><script type="application/ld+json">${JSON.stringify(articleLd)}</script>`;res.send(layout({title:`${p.title} — NovaHub`,description:p.meta_description,canonical:`${base(req)}/contenido/${p.slug}`,ogImage:p.media_url,body}))});

app.get('/sitemap.xml',(req,res)=>{const b=base(req), creators=db.prepare('SELECT slug FROM creators').all(),posts=db.prepare('SELECT slug FROM posts WHERE published=1').all();const urls=[`${b}/`,`${b}/about.html`,`${b}/privacy.html`,`${b}/terms.html`,`${b}/contact.html`,...creators.map(c=>`${b}/modelo/${c.slug}`),...posts.map(p=>`${b}/contenido/${p.slug}`)];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')}</urlset>`) });
app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nSitemap: ${base(req)}/sitemap.xml\n`));
app.get('/health',(req,res)=>res.json({ok:true,service:'NovaHub',time:new Date().toISOString()}));
app.listen(PORT,'0.0.0.0',()=>console.log(`NovaHub production running on :${PORT} using ${dbPath}`));
